### ISSUE TITLE
Turning speed of minimap/compass when using tb minimap as overlay

### ISSUE THREAD

**Issue by HiImFlo** [HasKha/GWToolboxpp#342] opened 2019-05-26 10:26 UTC
When using tb minimap as overlay for the normal compass, the turning speed is not the same which results in the enemies position not being the same when turning the camera.

Example: https://www.youtube.com/watch?v=ZJh05jnIzic

Make an option to give minimap the same turn delay as ingame compass.

**Comment by reduf** [comment] 2019-05-26 11:56
If we had such an option it wouldn't be an option, but the default behavior.

**Comment by HasKha** [comment] 2019-05-26 17:12
duplicate of #87

**Closed by HasKha** 2019-05-26 17:12 UTC
Labels: enhancement, minimap
