### ISSUE TITLE
corpses of masterless minions appear as enemies on the minimap

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#256] opened 2018-09-14 22:57 UTC
This is extremely distracting when they're supposed to be dead!

**Comment by Hour-of-the-Owl** [comment] 2018-09-16 00:16
pretty sure this is a bug, not an enhancement =P

**Comment by reduf** [comment] 2018-09-16 01:16
masterless minions aren't dead though, right ?

**Comment by GregLando113** [comment] 2018-09-16 02:05
theyre dead to me

**Comment by Hour-of-the-Owl** [comment] 2018-09-17 22:49
they still show up as red AFTER THEY DIE - that's the problem

**Comment by HasKha** [comment] 2018-09-24 23:37
truly undead.

**Comment by HasKha** [comment] 2018-09-29 18:03
both me and @Hour-of-the-Owl were unable to reproduce. Closing.

**Closed by HasKha** 2018-09-29 18:03 UTC
Labels: bug
