### ISSUE TITLE
Pcons Popping Auto + Turning Off

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#297] opened 2019-02-10 21:56 UTC
TB is turning off cons and pcons upon entering an area. also candy corn pcons spammed almost 100 in last 2 doa runs. TB spammed cons, almost 40 cons were used up in one run

By Frosty Bottom [Fail] in Teamspeak3

**Comment by reduf** [comment] 2019-02-12 21:09
Duplicate of #199

**Closed by reduf** 2019-02-12 21:09 UTC
Labels: duplicate
