### ISSUE TITLE
recast timer for skills

### ISSUE THREAD

**Issue by takepen** [HasKha/GWToolboxpp#241] opened 2018-07-31 09:09 UTC
just a timer for the recast time like the screenshot. maybe for Adrenaline too
![tb](https://user-images.githubusercontent.com/35411980/43450095-3f17ed08-94b2-11e8-87db-67686bcb850d.png)

**Comment by HasKha** [comment] 2018-07-31 18:55
duplicate of #37 

copying the screenshot over there for reference

**Closed by HasKha** 2018-07-31 18:55 UTC
