### ISSUE TITLE
spamming pcons

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#199] opened 2018-04-10 09:27 UTC
I'd heard of this before but never had it happen until today: TB was auto-popping my pcons much faster than it should have been. Eggs and War Supplies popped several times a second (so I quickly turned them off) and the 10-minute pcons re-popped after about 5 minutes. Lunars and alcohol were still working correctly.

Re-launching TB changed nothing. I then restarted GW and pcons worked correctly again. Re-zoning might have also fixed it, but I didn't wait to try that.

I was using the 2.11 beta.

**Comment by HasKha** [comment] 2018-06-19 19:58
Sorry for that. 

I'm going to close this. No way to reproduce and happened on 2.11 beta. I'll assume it's fixed. Please open a new issue if it happens again.

**Comment by 3vcloud** [comment] 2019-02-13 10:39
This is presuming that the problem is a dicky effect ptr, and that 1000ms is a reasonable wait time between spamming pcons in explorable areas...

1. Add a variable for pcon duration in `Pcon::Pcon` e.g. apples is 60000 * 10 ms.
2. Pcon is used. Don't use another one until **either**...
 a) If we find the relevent effect via `PconGeneric::CanUseByEffect` with a `GetTimeRemaining` of more than 1000ms
 b) We have a 1000ms timeout after use in which `Update` will keep checking the item ID of the last used stack to see if qty has changed (or ptr is null i.e. used last one).
3. In both cases, assign a variable that tells us (within a -2000ms margin to compensate for case b)) at what time the pcon was used.
 a) Note: If at any time the player is dead in a call to `Update`, and the pcon doesn't remain through death, the variable in step 3 is set to 0.
4. When deciding if we can use a pcon, we check the variable from step 3 against the duration variable in step 1. If the difference is < 1000ms then we can pop another one.

...And this could be tested by forcing the effect ptr to `nullptr` via `PconGeneric::CanUseByEffect`.

Thoughts on this?

**Comment by reduf** [comment] 2019-02-13 17:10
At this point I would rather hook the packets to keep track of the item timer myself.

**Comment by 3vcloud** [comment] 2019-02-13 17:16
Is there already a way in GWCA where I can hook into all StoC packets without defining a header, to find out which packet headers do what? Obviously I wouldn't use a generic hook for production code, but it would be good to know for my debugging (and I am aware that it'll be spammed when turned on)

**Comment by 3vcloud** [comment] 2019-03-01 10:48
Just having a coffee today and realised something - The `AgentEffects` struct has an `AgentId` field, but we're not checking it.

https://github.com/HasKha/GWToolboxpp/blob/a0b92f66461139744ceb19e972ae7c731fcd63a3/GWToolbox/GWToolbox/Windows/Pcons.cpp#L197

Instead of presuming that the first element of the array is our own, shouldn't we be checking against the AgentId within each array element? Is it possible that our own effect array isn't the first one populated on instance load?

https://github.com/GregLando113/GWCA/blob/a090e04d4a418eb5f7339a08d3ad450ad94bfd4b/GWCA/GameEntities/Skill.h#L118

This doesn't completely explain why the problem is only fixed on a Windows restart, but Windows does all sorts of witchcraft with recycling process memory even when its re-opened that is beyond me anyway.

**Comment by reduf** [comment] 2019-03-01 14:27
The problem is fix when restarting Guild Wars and I would be interested to know if the problem is fix if rezoning.

Moreover, it would indeed be better to ensure that this effects array is for the player agent no mater what.

**Comment by 3vcloud** [comment] 2019-03-01 14:29
I've had 2 people tell me that they have to restart _Windows_ to fix the problem, and restarting _Guild Wars_ doesn't help which brought up the discussion about timestamps.

**Comment by reduf** [comment] 2019-07-20 11:45
I'll consider this issue as resolved since we didn't hear about the bug for few months.
Will be re-openned if it happens again.

**Closed by reduf** 2019-07-20 11:45 UTC
Labels: bug
