### ISSUE TITLE
toolbox not saving window and widget positions

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#149] opened 2018-01-10 19:40 UTC
note: probably an imgui issue, but look into it

**Comment by HasKha** [comment] 2018-02-06 17:02
I've looked into it before releasing 2.6. I managed to have it happen a few times in 2.5 but could not reproduce reliably, and never noticed any issues in the saved file. I tried setting one or more values to 0 or -1 to test your theory, but toolbox loads correctly out-of-screen positions, so probably not an imgui issue.

**Comment by HasKha** [comment] 2018-02-06 17:03
https://www.reddit.com/r/GuildWars/comments/7vlsdu/gw_toolbox_problemsquestions/

**Comment by smiley232** [comment] 2018-02-08 12:39
I think the problem exists since toolbox 2.3 and it seems it is triggered by window mode. I testet with toolbox 2.2 and the problem is gone.
Steps to reproduce:
-set GW to full screen mode (did not test it with borderless full screen)
-move widgets to a position of the right side of the window (the part that is cut off when you go to window mode)
-go to window mode
-go to full screen

**Comment by reduf** [comment] 2018-06-08 20:19
Fixed in 4110c02

**Closed by reduf** 2018-06-08 20:19 UTC
Labels: bug
