### ISSUE TITLE
PCONS Timer

### ISSUE THREAD

**Issue by waldenpond1** [HasKha/GWToolboxpp#257] opened 2018-09-15 08:45 UTC
The apple and rock candies, and the other pcons items are constantly being used up every 2 seconds. 
The timer for the pcons is not working.

**Comment by HasKha** [comment] 2018-09-17 20:07
sorry about that. 

Duplicate of #199, which is still unresolved. Same note applies, I don't how to replicate and solve this.

**Comment by reduf** [comment] 2019-02-12 21:08
Close this issue, because duplicate.

**Closed by reduf** 2019-02-12 21:08 UTC
Labels: bug, critical
